Delete gradle/gradle-daemon-jvm.properties
No need to configure it, `org.gradle.toolchains.foojay-resolver-convention` will download toolchains automatically. This prop will result in edge issues like:

```
net.rubygrapefruit.platform.NativeException: Cannot determine architecture from kernel architecture name '13th Gen Intel(R) Core(TM) i5-13600KF'.
  at net.rubygrapefruit.platform.internal.MutableSystemInfo.getArchitecture(MutableSystemInfo.java:65)
  at net.rubygrapefruit.platform.internal.DefaultSystemInfo.getArchitecture(DefaultSystemInfo.java:48)
  at org.gradle.platform.internal.CurrentBuildPlatform.getArchitecture(CurrentBuildPlatform.java:62)
  at org.gradle.platform.internal.CurrentBuildPlatform.access$000(CurrentBuildPlatform.java:36)
  at org.gradle.platform.internal.CurrentBuildPlatform$1.get(CurrentBuildPlatform.java:47)
  at org.gradle.platform.internal.CurrentBuildPlatform$1.get(CurrentBuildPlatform.java:44)
  at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:198)
  at org.gradle.platform.internal.CurrentBuildPlatform.getArchitecture(CurrentBuildPlatform.java:58)
  at org.gradle.platform.internal.CurrentBuildPlatform.toBuildPlatform(CurrentBuildPlatform.java:93)
  at org.gradle.launcher.daemon.toolchain.DaemonJavaToolchainProvisioningService.getBuildPlatformToolchainUrl(DaemonJavaToolchainProvisioningService.java:113)
  at org.gradle.launcher.daemon.toolchain.DaemonJavaToolchainProvisioningService.tryInstall(DaemonJavaToolchainProvisioningService.java:73)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:229)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$query$2(JavaToolchainQueryService.java:199)
  at java.base/java.util.Optional.orElseGet(Optional.java:364)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.query(JavaToolchainQueryService.java:199)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$resolveToolchain$1(JavaToolchainQueryService.java:166)
  at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.resolveToolchain(JavaToolchainQueryService.java:164)
  at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$findMatchingToolchain$0(JavaToolchainQueryService.java:142)
  at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)
  at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
  at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
  at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:111)
```